version: '3'
services: 

  web:
    build: ./web
    volumes: 
      - ./web:/usr/src/app
    ports: 
      - 8000:8000
    command: gunicorn featured_list.wsgi:application  -b 0.0.0.0:8000

  nginx:
    restart: always
    build: ./nginx/
    volumes_from: 
      - web
    ports:
      - 80:8000
    links:
      - web