version: '2'
services: 

  web:
    build: ./web
    volumes: 
      - ./web:/usr/src/app
    expose:
      - "8000"
    command: gunicorn featured_list.wsgi:application  -b 0.0.0.0:8000

  nginx:
    restart: always
    build: ./nginx/
    volumes_from: 
      - web
    expose: 
      - "80"
    ports:
      - "8000:80"
    links:
      - web