version: '2'
services: 

  web:
    build: ./web
    expose:
      - "8000"
    command: python3 manage.py runserver 0.0.0.0:8000

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "8000:80"
    links:
      - web